select * from brasil WHERE taxa_ocupados_carteira is NULL
select * from brasil WHERE taxa_ocupados_carteira is not NULL
SELECT null + 1
select SUM( taxa_ocupados_carteira) from brasil 
-- varchar = texto int = inteiro data = data - transformar tudo em decimal
alter TABLE brasil alter COLUMN taxa_ocupados_carteira DECIMAL (10,2)
SELECT taxa_ocupados_carteira from brasil

-- Limpeza da Base--
select * from brasil
alter TABLE brasil alter COLUMN taxa_ocupados_carteira DECIMAL (10,2)
alter TABLE brasil alter COLUMN expectativa_vida DECIMAL (10,2)

alter TABLE brasil alter COLUMN  expectativa_vida DECIMAL (10,2)
alter TABLE brasil alter COLUMN  fecundidade_total DECIMAL (10,2)
alter TABLE brasil alter COLUMN  mortalidade_1 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  mortalidade_5 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  razao_dependencia DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prob_sobrevivencia_40 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prob_sobrevivencia_60 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_envelhecimento DECIMAL (10,2)
alter TABLE brasil alter COLUMN  expectativa_anos_estudo DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_analfabetismo_11_a_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_analfabetismo_15_a_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_analfabetismo_15_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_analfabetismo_18_a_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_analfabetismo_18_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_analfabetismo_25_a_29 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_analfabetismo_25_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_0_basico DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_0_fundamental DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_0_medio DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_1_basico DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_1_fundamental DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_1_medio DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_2_basico DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_2_fundamental DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atraso_2_medio DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_bruta_basico DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_bruta_fundamental DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_bruta_medio DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_bruta_pre DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_bruta_superior DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_liquida_basico DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_liquida_fundamental DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_liquida_medio DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_liquida_pre DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_liquida_superior DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_0_3 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_11_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_18_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_25_29 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_4_5 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_4_6 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_5_6 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_6 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_6_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_6_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_fundamental_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_fundamental_18_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_fundamental_4_5 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_medio_18_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_medio_6_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_freq_superior_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_fundamental_11_13 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_fundamental_12_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_fundamental_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_fundamental_16_18 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_fundamental_18_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_fundamental_18_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_fundamental_25_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_medio_18_20 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_medio_18_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_medio_18_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_medio_19_21 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_medio_25_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_superior_25_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_max_quintil_1 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_max_quintil_2 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_max_quintil_3 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_max_quintil_4 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_max_decil_9 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  indice_gini DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_pobreza_extrema DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_pobreza_extrema_criancas DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_pobreza DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_pobreza_criancas DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_vulner_pobreza DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_vulner_pobreza_criancas DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_renda_10_ricos DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_renda_20_pobres DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_renda_20_ricos DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_renda_40_pobres DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_renda_60_pobres DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_renda_80_pobres DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_renda_trabalho DECIMAL (10,2)
alter TABLE brasil alter COLUMN  razao_10_ricos_40_pobres DECIMAL (10,2)
alter TABLE brasil alter COLUMN  razao_20_ricos_40_pobres DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_quintil_1 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_decil_10 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_quintil_2 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_quintil_3 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_quintil_4 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_quintil_5 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_exc_renda_nula DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_pobreza_extrema DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_pobreza DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_pc_vulner_pobreza DECIMAL (10,2)
alter TABLE brasil alter COLUMN  indice_theil DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_trabalhadores_conta_proria DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_empregadores DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_agropecuaria DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_comercio DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_construcao DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_extracao DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_formalizacao DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_fundamental DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_medio DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_servicos DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_siup DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_superior DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_transformacao DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_renda_0 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_renda_1_sm DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_renda_2_sm DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_renda_3_sm DECIMAL (10,2)
alter TABLE brasil alter COLUMN  prop_ocupados_renda_5_sm DECIMAL (10,2)
alter TABLE brasil alter COLUMN  renda_media_ocupados DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atividade DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atividade_10_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atividade_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atividade_18_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atividade_18_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_atividade_25_29 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_desocupacao DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_desocupacao_10_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_desocupacao_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_desocupacao_18_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_desocupacao_18_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_desocupacao_25_29 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  indice_treil_trabalho DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_ocupados_carteira DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_ocupados_setor_publico DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_ocupados_sem_carteira DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_agua_encanada DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_banheiro_agua_encanada DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_densidade_2_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_coleta_lixo DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_energia_eletrica DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_agua_esgoto_inadequados DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_paredes_inadequados DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_criancas_dom_sem_fund DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_criancas_fora_escola_4_5 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_criancas_fora_escola_6_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_dom_sem_fund DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_dom_vulner_sem_fund DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_sem_fund_informal DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_mulheres_com_filho_10_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_mulheres_com_filho_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_mulheres_chefe_filho_15m DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_nest_ntrab_vulner_15_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_vulner_desloc_1_hora DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_dom_vulner_dep_idoso DECIMAL (10,2)
alter TABLE brasil alter COLUMN  taxa_sem_energia_eletrica DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_0_4 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_10_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_15_19 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_20_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_25_29 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_30_34 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_35_39 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_40_44 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_45_49 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_50_54 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_55_59 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_5_9 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_60_64 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_65_69 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_70_74 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_75_79 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_homens_80_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_0_4 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_10_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_15_19 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_20_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_25_29 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_30_34 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_35_39 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_40_44 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_45_49 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_50_54 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_55_59 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_5_9 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_60_64 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_65_69 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_70_74 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_75_79 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres_80_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_mulheres DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_1_menos DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_11_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_11_13 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_12_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_1_3 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_15_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_15_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_16_18 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_18_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_18_20 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_18_24 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_19_21 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_25_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_4 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_5 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_6 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_6_10 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_6_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_65_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_urbana DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_rural DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_dom_pp DECIMAL (10,2)
alter TABLE brasil alter COLUMN  populacao_dom_pp_exc_renda_nula DECIMAL (10,2)
alter TABLE brasil alter COLUMN  pea DECIMAL (10,2)
alter TABLE brasil alter COLUMN  pea_10_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  pea_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  pea_18_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  pia DECIMAL (10,2)
alter TABLE brasil alter COLUMN  pia_10_14 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  pia_15_17 DECIMAL (10,2)
alter TABLE brasil alter COLUMN  pia_18_mais DECIMAL (10,2)
alter TABLE brasil alter COLUMN  indice_escolaridade DECIMAL (10,2)
alter TABLE brasil alter COLUMN  indice_frequencia_escolar DECIMAL (10,2)
alter TABLE brasil alter COLUMN  idhm DECIMAL (10,2)
alter TABLE brasil alter COLUMN  idhm_e DECIMAL (10,2)
alter TABLE brasil alter COLUMN  idhm_l DECIMAL (10,2)
alter TABLE brasil alter COLUMN  idhm_r INT (10)


SELECT idhm_r FROM brasil
(idhm_r * 100)


-- 1) Qual é o sexo biológico que nasce mais a cada década passada?
SELECT ano, populacao_homens_0_4, populacao_mulheres_0_4 FROM brasil

-- 2) Qual o sexo biologico com população em cada década?

SELECT ano, populacao_homens, populacao_mulheres from brasil

-- 3) Qual o sexo biologico com maior população com idosos de 80 anos ou mais?

SELECT ano, populacao_homens_80_mais, populacao_mulheres_80_mais from brasil

-- 4) Qual a expectativa de vida por decada? 

SELECT ano, expectativa_vida from brasil











